import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

export type Lang = "id" | "en";

type Dict = Record<string, { id: string; en: string }>;

const dict = {
  "nav.features": { id: "Fitur", en: "Features" },
  "nav.pricing": { id: "Harga", en: "Pricing" },
  "nav.faq": { id: "FAQ", en: "FAQ" },
  "nav.signin": { id: "Masuk", en: "Sign in" },
  "nav.start": { id: "Mulai gratis", en: "Start free" },
  "nav.dashboard": { id: "Dasbor", en: "Dashboard" },
  "nav.signout": { id: "Keluar", en: "Sign out" },

  "hero.badge": { id: "Untuk era vibe coding", en: "Built for the vibe coding era" },
  "hero.title": {
    id: "Review code AI seperti senior developer — cepat & minim noise.",
    en: "Review AI-generated code like a senior dev — fast and noise-free.",
  },
  "hero.subtitle": {
    id: "GuardAI membantu kamu menjaga kualitas, test coverage, dan keamanan code yang dihasilkan Cursor, Claude Code, atau Lovable.",
    en: "GuardAI helps you keep quality, test coverage, and security high for code generated by Cursor, Claude Code, or Lovable.",
  },
  "hero.cta": { id: "Coba gratis", en: "Try it free" },
  "hero.cta2": { id: "Lihat demo", en: "See demo" },
  "hero.trust": {
    id: "10 review gratis tiap bulan • Tanpa kartu kredit",
    en: "10 free reviews per month • No credit card",
  },

  "features.title": { id: "Semua yang kamu butuhkan untuk PR yang bersih", en: "Everything you need for cleaner PRs" },
  "features.subtitle": {
    id: "Dirancang khusus untuk code yang dihasilkan AI — bukan sekadar linter.",
    en: "Built specifically for AI-generated code — not just another linter.",
  },
  "f1.t": { id: "Review AI kontekstual", en: "Context-aware AI review" },
  "f1.d": { id: "Komentar inline dengan severity dan saran fix yang langsung bisa dipakai.", en: "Inline comments with severity and ready-to-apply fix suggestions." },
  "f2.t": { id: "Auto test generator", en: "Auto test generator" },
  "f2.d": { id: "Generate unit & integration test plus edge case dari code yang kamu paste.", en: "Generate unit & integration tests plus edge cases from the code you paste." },
  "f3.t": { id: "Security scanner", en: "Security scanner" },
  "f3.d": { id: "Deteksi OWASP Top 10 dan kerentanan umum di code AI.", en: "Detect OWASP Top 10 and common AI-generated vulnerabilities." },
  "f4.t": { id: "Framework-specific", en: "Framework-specific" },
  "f4.d": { id: "Aturan khusus Next.js, Laravel, TypeScript, Flutter, dan lainnya.", en: "Dedicated rules for Next.js, Laravel, TypeScript, Flutter, and more." },
  "f5.t": { id: "Custom guidelines", en: "Custom guidelines" },
  "f5.d": { id: "Tempel style guide tim — AI akan ikut aturan kamu.", en: "Paste your team style guide — AI will follow your rules." },
  "f6.t": { id: "Cepat & ringkas", en: "Fast & focused" },
  "f6.d": { id: "Review <25 detik untuk file <200KB. Tanpa noise berlebihan.", en: "Reviews under 25s for files under 200KB. No excessive noise." },

  "pricing.title": { id: "Harga sederhana, transparan", en: "Simple, transparent pricing" },
  "pricing.subtitle": { id: "Mulai gratis. Upgrade saat kamu butuh.", en: "Start free. Upgrade when you need to." },
  "plan.free": { id: "Free", en: "Free" },
  "plan.pro": { id: "Pro", en: "Pro" },
  "plan.team": { id: "Team", en: "Team" },
  "plan.month": { id: "/bulan", en: "/month" },
  "plan.free.tag": { id: "Untuk mencoba", en: "Try it out" },
  "plan.pro.tag": { id: "Untuk solo & freelancer", en: "Solo & freelancers" },
  "plan.team.tag": { id: "Untuk tim kecil", en: "Small teams" },
  "plan.popular": { id: "Paling Populer", en: "Most Popular" },
  "plan.cta": { id: "Pilih paket", en: "Choose plan" },
  "plan.free.cta": { id: "Mulai gratis", en: "Start free" },

  "faq.title": { id: "Pertanyaan umum", en: "Frequently asked questions" },
  "faq.q1": { id: "Apakah code saya disimpan?", en: "Is my code stored?" },
  "faq.a1": { id: "Tidak. Code tidak disimpan permanen kecuali kamu memintanya.", en: "No. Code is not permanently stored unless you opt in." },
  "faq.q2": { id: "Framework apa saja yang didukung?", en: "Which frameworks are supported?" },
  "faq.a2": { id: "Next.js (App Router), Laravel, TypeScript, dan Flutter di MVP. Lainnya menyusul.", en: "Next.js (App Router), Laravel, TypeScript, and Flutter at MVP. More coming soon." },
  "faq.q3": { id: "Apakah ada integrasi GitHub?", en: "Is there GitHub integration?" },
  "faq.a3": { id: "GitHub App akan tersedia di iterasi berikutnya. Saat ini gunakan review manual di dasbor.", en: "GitHub App is coming in the next iteration. For now use manual review in the dashboard." },
  "faq.q4": { id: "Bagaimana cara membayar?", en: "How can I pay?" },
  "faq.a4": { id: "Pembayaran via Stripe dan Midtrans akan hadir bersama paket Pro. Saat ini semua user gratis selama beta.", en: "Stripe and Midtrans billing arrive with the Pro plan. For now everyone is free during beta." },

  "cta.title": { id: "Siap kirim code yang lebih bersih?", en: "Ready to ship cleaner code?" },
  "cta.sub": { id: "Tidak perlu kartu kredit. Mulai dalam 30 detik.", en: "No credit card. Get started in 30 seconds." },

  "footer.tag": { id: "Second pair of eyes untuk developer AI-era.", en: "Second pair of eyes for AI-era developers." },
  "footer.rights": { id: "Hak cipta dilindungi.", en: "All rights reserved." },

  "auth.title": { id: "Masuk ke akunmu", en: "Sign in to your account" },
  "auth.subtitle": { id: "Atau buat akun baru — gratis.", en: "Or create a new account — it's free." },
  "auth.email": { id: "Email", en: "Email" },
  "auth.password": { id: "Kata sandi", en: "Password" },
  "auth.signin": { id: "Masuk", en: "Sign in" },
  "auth.signup": { id: "Daftar", en: "Sign up" },
  "auth.google": { id: "Lanjut dengan Google", en: "Continue with Google" },
  "auth.or": { id: "atau", en: "or" },
  "auth.toggleToSignup": { id: "Belum punya akun? Daftar", en: "No account yet? Sign up" },
  "auth.toggleToSignin": { id: "Sudah punya akun? Masuk", en: "Already have an account? Sign in" },
  "auth.back": { id: "Kembali ke beranda", en: "Back to home" },
  "auth.github": { id: "Lanjut dengan GitHub", en: "Continue with GitHub" },

  "dash.title": { id: "Manual Code Review", en: "Manual Code Review" },
  "dash.subtitle": { id: "Tempel code, pilih bahasa & framework, dapatkan review + test + scan keamanan.", en: "Paste code, choose language & framework, get review + tests + security scan." },
  "dash.code": { id: "Code", en: "Code" },
  "dash.codePlaceholder": { id: "Tempel code di sini…", en: "Paste your code here…" },
  "dash.language": { id: "Bahasa", en: "Language" },
  "dash.framework": { id: "Framework (opsional)", en: "Framework (optional)" },
  "dash.guidelines": { id: "Custom guidelines (opsional)", en: "Custom guidelines (optional)" },
  "dash.guidelinesPh": { id: "Mis. selalu pakai async/await, hindari any, dst.", en: "e.g. always use async/await, avoid any, etc." },
  "dash.run": { id: "Jalankan review", en: "Run review" },
  "dash.running": { id: "Menganalisis…", en: "Analyzing…" },
  "dash.empty": { id: "Hasil review akan muncul di sini.", en: "Review results will appear here." },
  "dash.summary": { id: "Ringkasan", en: "Summary" },
  "dash.quality": { id: "Quality score", en: "Quality score" },
  "dash.findings": { id: "Findings", en: "Findings" },
  "dash.security": { id: "Security", en: "Security" },
  "dash.tests": { id: "Generated tests", en: "Generated tests" },
  "dash.line": { id: "Baris", en: "Line" },
  "dash.noFindings": { id: "Tidak ada temuan. Code terlihat bersih.", en: "No findings. The code looks clean." },
  "dash.error": { id: "Gagal menjalankan review. Coba lagi.", en: "Review failed. Please try again." },
  "dash.copy": { id: "Salin", en: "Copy" },
  "dash.copied": { id: "Tersalin", en: "Copied" },
  "dash.saved": { id: "Review tersimpan ke riwayat", en: "Review saved to history" },
  "dash.history": { id: "Riwayat", en: "History" },
  "dash.newReview": { id: "Review baru", en: "New review" },

  "hist.title": { id: "Riwayat Review", en: "Review History" },
  "hist.subtitle": { id: "Semua review yang pernah kamu jalankan.", en: "All your past reviews." },
  "hist.empty": { id: "Belum ada riwayat. Jalankan review pertamamu.", en: "No history yet. Run your first review." },
  "hist.score": { id: "Skor", en: "Score" },
  "hist.findings": { id: "Findings", en: "Findings" },
  "hist.security": { id: "Security", en: "Security" },
  "hist.view": { id: "Lihat", en: "View" },
  "hist.delete": { id: "Hapus", en: "Delete" },
  "hist.deleted": { id: "Review dihapus", en: "Review deleted" },
  "hist.confirmDelete": { id: "Hapus review ini?", en: "Delete this review?" },
  "hist.back": { id: "Kembali ke riwayat", en: "Back to history" },
  "hist.code": { id: "Code yang direview", en: "Reviewed code" },

  "nav.review": { id: "Review", en: "Review" },
  "nav.prs": { id: "PR", en: "PRs" },
  "nav.history": { id: "Riwayat", en: "History" },
  "nav.more": { id: "Lainnya", en: "More" },
  "nav.integrations": { id: "Integrasi", en: "Integrations" },
  "prh.detail": { id: "Detail", en: "Details" },
  "prh.line": { id: "Baris", en: "Line" },
  "prh.summary": { id: "Ringkasan", en: "Summary" },
  "prh.tests": { id: "Saran Test", en: "Test Suggestions" },
  "prh.viewOnGh": { id: "Lihat di GitHub", en: "View on GitHub" },
  "prh.security": { id: "Keamanan", en: "Security" },
  "prh.findings": { id: "Temuan", en: "Findings" },
  "prh.score": { id: "Skor", en: "Score" },
  "prh.filterFailed": { id: "Gagal", en: "Failed" },
  "prh.filterSkipped": { id: "Dilewati", en: "Skipped" },
  "prh.filterRunning": { id: "Berjalan", en: "Running" },
  "prh.filterCompleted": { id: "Selesai", en: "Completed" },
  "prh.filterAll": { id: "Semua", en: "All" },
  "prh.empty": { id: "Belum ada review PR. Install GitHub App dan buat PR untuk memulai.", en: "No PR reviews yet. Install the GitHub App and create a PR to get started." },
  "prh.totalSecurity": { id: "Isu Keamanan", en: "Security Issues" },
  "prh.totalFindings": { id: "Temuan", en: "Findings" },
  "prh.avgScore": { id: "Rata-rata Skor", en: "Avg Score" },
  "prh.total": { id: "Total Review", en: "Total Reviews" },
  "prh.title": { id: "Riwayat Review PR", en: "PR Review History" },
  "nav.prHistory": { id: "Review PR", en: "PR Reviews" },
  "nav.guidelines": { id: "Guidelines", en: "Guidelines" },
  "nav.billing": { id: "Tagihan", en: "Billing" },
  "gh.title": { id: "Integrasi GitHub", en: "GitHub Integration" },
  "gh.subtitle": { id: "Pasang GitHub App agar setiap Pull Request otomatis direview.", en: "Install the GitHub App so every Pull Request gets reviewed automatically." },
  "gh.install": { id: "Pasang GitHub App", en: "Install GitHub App" },
  "gh.sync": { id: "Sinkronkan", en: "Sync" },
  "gh.syncNone": { id: "Tidak ada instalasi GitHub baru yang ditemukan.", en: "No new GitHub installation was found." },
  "gh.syncMultiple": { id: "Ada lebih dari satu instalasi baru. Klik Pasang GitHub App lagi agar akun yang benar bisa dipilih.", en: "More than one new installation was found. Click Install GitHub App again so the right account can be selected." },
  "gh.notConfigured": { id: "GitHub App belum di-setup oleh admin.", en: "GitHub App is not yet configured by the admin." },
  "gh.connected": { id: "Akun terhubung", en: "Connected accounts" },
  "gh.empty": { id: "Belum ada akun GitHub yang terhubung.", en: "No GitHub account connected yet." },
  "gh.repos": { id: "repo", en: "repos" },
  "gh.unlink": { id: "Putuskan", en: "Unlink" },
  "gh.linking": { id: "Menghubungkan instalasi…", en: "Linking installation…" },
  "gh.linked": { id: "GitHub App terhubung", en: "GitHub App connected" },
  "gh.prReviews": { id: "Review Pull Request", en: "Pull Request Reviews" },
  "gh.prEmpty": { id: "Belum ada review otomatis. Buka PR untuk memicu review pertama.", en: "No automatic reviews yet. Open a PR to trigger your first review." },
  "gh.status.running": { id: "Berjalan", en: "Running" },
  "gh.status.completed": { id: "Selesai", en: "Completed" },
  "gh.status.failed": { id: "Gagal", en: "Failed" },
  "gh.status.skipped": { id: "Dilewati", en: "Skipped" },
  "gh.viewPr": { id: "Lihat PR", en: "View PR" },
} satisfies Dict;

export type TKey = keyof typeof dict;

const LangCtx = createContext<{ lang: Lang; setLang: (l: Lang) => void; t: (k: TKey) => string }>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
});

export function I18nProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>("en");

  useEffect(() => {
    const stored = (typeof window !== "undefined" && localStorage.getItem("lang")) as Lang | null;
    if (stored === "id" || stored === "en") {
      setLangState(stored);
      return;
    }
    if (typeof navigator !== "undefined" && navigator.language.toLowerCase().startsWith("id")) {
      setLangState("id");
    }
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    if (typeof window !== "undefined") localStorage.setItem("lang", l);
  };

  const t = (k: TKey) => dict[k][lang];

  return <LangCtx.Provider value={{ lang, setLang, t }}>{children}</LangCtx.Provider>;
}

export function useI18n() {
  return useContext(LangCtx);
}
